
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zljnumbeggkcwudtmtlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpsam51bWJlZ2drY3d1ZHRtdGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyOTY2NzAsImV4cCI6MjA1ODg3MjY3MH0.Gf5qcBVG-3G386WpjGwTAlI4Jp8ciFHKOCHNWeNwN08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
